- name: Add Mongo Repository
  yum_repository:
    name: MongoDB
    description: MongoDB Repository
    baseurl: https://repo.mongodb.org/yum/redhat/$releasever/mongodb-org/4.2/x86_64/
    enabled: yes
    gpgcheck: yes
    gpgkey: https://www.mongodb.org/static/pgp/server-4.2.asc' >/etc/yum.repos.d/mongodb.repo
    file: mongodb

- name: Install MongoDB
  yum:
    name: mongodb-org
    state: present

- name: Update MongoDB listen Address
  ansible.builtin.replace:
    path: /etc/mongod.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'
  notify:
    - Restart MongoDB

- name: Start MongoDB service
  systemd:
    name: mongodb
    enabled: yes
    state: started

- name: Download Package
  include_role:
    name: common
    tasks_from: download-from-github
  vars:
    APP_DIR: /tmp/mongodb-main
    EXTRACT_DIR: /tmp

- name: Load Schema
  community.mongodb.mongodb_shell:
    file: "/tmp/mongodb-main/{{item}}"
    idempotent: yes
  loop:
    - users.js
    - catalouge.js





  