- name: Demo on Variables
  hosts: all
  vars:
    URL: play.example.com
  tasks:
    - name: Print Variable
      debug: #{ msg : "Hello World"}
        msg: URL = {{ URL }}
    - name: Print variables from task
      vars:
        URL: task.example.com
      debug:
        msg: URL = {{ URL }}

- name: Demo Variables from files
  hosts: all
  vars_files:
    - example-vars.yml
  tasks:
    - name: Print Variable
      debug:
        msg: URL == {{ URL }}

- name: Demo on variables from user input
  hosts: all
  vars_prompt:
    - name: URL
      prompt: Enter URL
      private: no
  tasks:
    - name: Print Variable
      debug:
        msg: URL == {{ URL }}

- name: Demo on variables from inventory
  hosts: all
  tasks:
    - name: Print Variable
      debug:
        msg: URL == {{ URL }}